### ISSUE TITLE
Bluetooth permission was asked during onboarding

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1355]
Description:

User made fresh installation of app, then went through onboarding slides

Actual: user was shown Bluetooth permission popup when he was on signin page.
Expected: should ask only when it's necessary

- User is adding new sensor first time on Add New Sensors
- User signed into cloud and is using mixed mode

**Comment by markoaamunkajo** [comment]
Not high priority for now, moved to 2.3

**Comment by priyonto** [comment]
Found it. Its how BTKit is implemented and used on the app. And, I would prefer not to do anything about it since its going to affect the whole BT scanning mechanism across the application. And, the outcome is not also not something significant from all those changes even if we do it.

**Comment by markoaamunkajo** [comment]
Closing this, will be handled in BTKit repository with card https://github.com/ruuvi/BTKit/issues/1

**Comment by markoaamunkajo** [comment]
Reopened, this issue was not handled due to not being on board.

**Comment by rinat-enikeev** [comment]
fixed in https://github.com/ruuvi/com.ruuvi.station.ios/pull/1925 and https://github.com/ruuvi/BTKit/pull/13

**Comment by DG12** [comment]
The request for permission to bluetooth, even though the instance of station has been running for a while(?) and Bluetooth access is already granted, occurs very rarely. Is there a way to check permission and if (seemly not) check a second time?

For me,  VERY minor issue but I thought I should let you know.

**Comment by markoaamunkajo** [comment]
@rinat-enikeev 2.6.0 (2402061941)

If I open app and leave it untouched on first onboarding for a few minutes I will see permission popup.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/36391cfc-10bb-4754-9f94-e15e96cfd2e4)

**Comment by markoaamunkajo** [comment]
2.6.1 (2402111104) Firebase build. Still shows if user keeps the code screen open for a while.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/67144384-a952-4f4c-88b4-f9a6ec793f2f)

**Comment by markoaamunkajo** [comment]
@rinat-enikeev Was the BTKit side fix already done? Can this be then fixed on the app side already?
