### ISSUE TITLE
No alarm although humidity is out of alert limit 1.1.0 (285)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#888]
RUUVI_450A (notice underscore) has no alarm but
current temp: 72.9 , alert: 41---88
current humidity: 39.77, alert: 60--78  <<<<
AirPressure, RSSI & movement alerts off
update 2 s ago

Webui correctly shows humidity alarm as does android.

**Comment by laurijamsa** [comment]
Meaning, humidity alerts are broken on 1.1.0 (285)? What about other alerts? Let's test this @markoaamunkajo

**Comment by priyonto** [comment]
This one seems to be broken in earlier versions too, not only in the 1.1.0(285). The issue is spotted and a fix is on the way.

**Comment by priyonto** [comment]
@DG12 When you say no alarm, does it mean when the humidity is under or above threshold you are not getting any email alert? Or the little warning beside the humidity is not showing?

**Comment by priyonto** [comment]
Update: I have tested the alert and the email and local alert seems to be working as expected. But, I noticed the warning is not showing is not beside the humidity text. I have fixed on the above commit.

**Comment by markoaamunkajo** [comment]
@priyonto Maybe this is the actual case: I previously had humidity units set to % and had alert going to my email. Then configured humidity units to dew point, went back to configure new alert but I still see alert showing % and I get humidity alert for % going to my email.

https://user-images.githubusercontent.com/50437378/166086051-ae430628-de51-4e60-8585-32dc8ef097a3.mov

Expected:
I should see alert for dew and should be able to configure it. The % alert should not be in use.

**Comment by laurijamsa** [comment]
> Expected:\nI should see alert for dew and should be able to configure it. The % alert should not be in use.

This is not correct because we don't support other than relative humidity alerts.

**Comment by markoaamunkajo** [comment]
Ahh I'm thinking about some prehistorical build, my bad.
Custom texts, alert emails and limits were checked, all good for me in this build. Moving to done.

**Comment by DG12** [comment]
Bell symbol did not blink
Need to check most recent version

**Comment by DG12** [comment]
I.e. bell symbol does not blink. 
Emails received .

PS spamassassin added to the spam score just a little because:
"From and EnvelopeFrom 2nd level mail domains are different."

PPS is there an option for Appdistribution.firebase.google.com to retain data? 
or did (288) require data to be deleted?

**Comment by markoaamunkajo** [comment]
QA passed
